---
  deployment:
    tasks:
      # set project public folder or deployment folder
      - export DEPLOYPATH=/home/refhcare/public_html/jrmlagagne
      - export REPOPATH=/home/refhcare/repositories/jrmlagagne
      - export DATAPATH=/home/refhcare/repositories/data/jrmlagagne

      # copy contents of the public folder alongside composer.json and composer lock into public folder
      - cp -r $REPOPATH/public/* $DEPLOYPATH
      - cp -r $REPOPATH/public/.* $DEPLOYPATH
      - yes | cp $REPOPATH/composer.json $DEPLOYPATH
      - yes | cp $REPOPATH/composer-lock.json $DEPLOYPATH
      - yes | cp $DATAPATH/.env $DEPLOYPATH
      - yes | cp $DATAPATH/.htaccess $DEPLOYPATH
      - yes | cp $DATAPATH/index.php $DEPLOYPATH

      - chmod -R 0777 $DEPLOYPATH/public
      - chmod -R 0777 $REPOPATH/public

      # install composer packages both in project repository and deployment root
      - composer install --working-dir=$REPOPATH --no-dev --optimize-autoloader
      - composer install --working-dir=$DEPLOYPATH --no-dev --optimize-autoloader
      - cd $DEPLOYPATH
      - php artisan optimize:clear
      - php artisan cache:config
      - cd $REPOPATH
      - php artisan optimize:clear
      - php artisan cache:config
