# This is a basic workflow to help you get started with Actions

name: Build And Deploy

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy referencehealthcare.org
                uses: appleboy/ssh-action@v0.1.4
                with:
                    host: ${{ secrets.NAMECHEAP_CD_SSH_HOST }}
                    port: ${{ secrets.NAMECHEAP_CD_SSH_PORT }}
                    username: ${{ secrets.NAMECHEAP_CD_SSH_USERNAME }}
                    password: ${{ secrets.NAMECHEAP_CD_SSH_PASSWORD }}

                    script: |
                        cd ~/public_html/
                        git pull
                        cp ~/data/.env ~/public_html/.env
                        composer install
                        bin/console doctrine:migrations:migrate --no-interaction
                        bin/console cache:clear        
                        echo "Deployment successful!"
